version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  backend:
    build: ./prox
    ports:
      - "3001:3001"
  ai_backend:
    build: ./ai_backend
    ports:
      - "8000:8000"
